// Tipología / áreas de especialización del profesional (en lo que más destaca).
// Las mismas claves las usa quien pide ayuda para decir qué necesita; por eso
// hay dos juegos de etiquetas: `needLabels` (vista profesional / filtros del
// feed) y `needSeekerLabels` (lenguaje cálido para quien busca apoyo).
export const needCategories = [
  "infancia_adolescencia",
  "familia_pareja",
  "duelo",
  "ansiedad_depresion",
  "trauma_crisis",
  "adicciones",
  "autoestima",
  "orientacion_general",
  "otro",
] as const;

export const urgencyLevels = ["baja", "media", "alta"] as const;
export const languages = ["es", "en", "other"] as const;

// Etiquetas por ESPECIALIDAD: las ve el profesional al elegir sus áreas y se
// usan en los filtros y las tarjetas del feed público.
// Etiquetas enfocadas en LO QUE LE SUCEDIÓ a la persona (situación/evento), no en
// categorías clínicas genéricas. Cortas para servir también de "chip" en la
// tarjeta del feed. Las claves no cambian (no rompe datos ni emparejamiento).
export const needLabels: Record<(typeof needCategories)[number], string> = {
  infancia_adolescencia: "Algo en la niñez o adolescencia",
  familia_pareja: "Una ruptura o un conflicto de pareja o familia",
  duelo: "Una pérdida o un duelo",
  ansiedad_depresion: "Ansiedad o tristeza que no se va",
  trauma_crisis: "Vivió algo muy fuerte o violento",
  adicciones: "Consumo o una adicción",
  autoestima: "Un golpe a la autoestima",
  orientacion_general: "Un momento difícil, necesita hablar",
  otro: "Otra situación",
};

// Etiquetas cálidas para la persona que pide ayuda (mismas keys que needLabels).
// Preguntan por la persona, no por el dato, y dejan salidas de baja exposición.
export const needSeekerLabels: Record<(typeof needCategories)[number], string> =
  {
    infancia_adolescencia: "Algo que vive un niño, niña o adolescente",
    familia_pareja: "Algo con mi familia o mi pareja",
    duelo: "Un duelo o una pérdida",
    ansiedad_depresion: "Ansiedad, angustia o tristeza",
    trauma_crisis: "Pasé por algo muy fuerte",
    adicciones: "Consumo o adicciones",
    autoestima: "Autoestima o cómo me siento conmigo",
    orientacion_general: "No sé / solo necesito hablar",
    otro: "Prefiero no decirlo ahora",
  };

// Urgencia en lenguaje vivencial, no clínico: no obliga a autodiagnosticarse.
export const urgencyLabels: Record<(typeof urgencyLevels)[number], string> = {
  baja: "Puedo esperar unos días",
  media: "Me vendría bien pronto",
  alta: "Lo estoy pasando muy mal ahora",
};

export const languageLabels: Record<(typeof languages)[number], string> = {
  es: "Español",
  en: "Inglés",
  other: "Otro",
};

// Lista de países (nombres en español) para los selectores de "país" del perfil
// profesional (ubicación y país de la credencial). Cubre los estados miembros de
// la ONU + algunos observadores comunes. Orden alfabético; Venezuela es el
// default en el formulario por el público objetivo de la app.
export const countries = [
  "Afganistán",
  "Albania",
  "Alemania",
  "Andorra",
  "Angola",
  "Antigua y Barbuda",
  "Arabia Saudita",
  "Argelia",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaiyán",
  "Bahamas",
  "Bangladés",
  "Barbados",
  "Baréin",
  "Bélgica",
  "Belice",
  "Benín",
  "Bielorrusia",
  "Birmania (Myanmar)",
  "Bolivia",
  "Bosnia y Herzegovina",
  "Botsuana",
  "Brasil",
  "Brunéi",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Bután",
  "Cabo Verde",
  "Camboya",
  "Camerún",
  "Canadá",
  "Catar",
  "Chad",
  "Chile",
  "China",
  "Chipre",
  "Colombia",
  "Comoras",
  "Corea del Norte",
  "Corea del Sur",
  "Costa de Marfil",
  "Costa Rica",
  "Croacia",
  "Cuba",
  "Dinamarca",
  "Dominica",
  "Ecuador",
  "Egipto",
  "El Salvador",
  "Emiratos Árabes Unidos",
  "Eritrea",
  "Eslovaquia",
  "Eslovenia",
  "España",
  "Estados Unidos",
  "Estonia",
  "Esuatini (Suazilandia)",
  "Etiopía",
  "Filipinas",
  "Finlandia",
  "Fiyi",
  "Francia",
  "Gabón",
  "Gambia",
  "Georgia",
  "Ghana",
  "Granada",
  "Grecia",
  "Guatemala",
  "Guinea",
  "Guinea-Bisáu",
  "Guinea Ecuatorial",
  "Guyana",
  "Haití",
  "Honduras",
  "Hungría",
  "India",
  "Indonesia",
  "Irak",
  "Irán",
  "Irlanda",
  "Islandia",
  "Islas Marshall",
  "Islas Salomón",
  "Israel",
  "Italia",
  "Jamaica",
  "Japón",
  "Jordania",
  "Kazajistán",
  "Kenia",
  "Kirguistán",
  "Kiribati",
  "Kuwait",
  "Laos",
  "Lesoto",
  "Letonia",
  "Líbano",
  "Liberia",
  "Libia",
  "Liechtenstein",
  "Lituania",
  "Luxemburgo",
  "Macedonia del Norte",
  "Madagascar",
  "Malasia",
  "Malaui",
  "Maldivas",
  "Malí",
  "Malta",
  "Marruecos",
  "Mauricio",
  "Mauritania",
  "México",
  "Micronesia",
  "Moldavia",
  "Mónaco",
  "Mongolia",
  "Montenegro",
  "Mozambique",
  "Namibia",
  "Nauru",
  "Nepal",
  "Nicaragua",
  "Níger",
  "Nigeria",
  "Noruega",
  "Nueva Zelanda",
  "Omán",
  "Países Bajos",
  "Pakistán",
  "Palaos",
  "Palestina",
  "Panamá",
  "Papúa Nueva Guinea",
  "Paraguay",
  "Perú",
  "Polonia",
  "Portugal",
  "Reino Unido",
  "República Centroafricana",
  "República Checa",
  "República del Congo",
  "República Democrática del Congo",
  "República Dominicana",
  "Ruanda",
  "Rumanía",
  "Rusia",
  "Samoa",
  "San Cristóbal y Nieves",
  "San Marino",
  "San Vicente y las Granadinas",
  "Santa Lucía",
  "Santo Tomé y Príncipe",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leona",
  "Singapur",
  "Siria",
  "Somalia",
  "Sri Lanka",
  "Sudáfrica",
  "Sudán",
  "Sudán del Sur",
  "Suecia",
  "Suiza",
  "Surinam",
  "Tailandia",
  "Tanzania",
  "Tayikistán",
  "Timor Oriental",
  "Togo",
  "Tonga",
  "Trinidad y Tobago",
  "Túnez",
  "Turkmenistán",
  "Turquía",
  "Tuvalu",
  "Ucrania",
  "Uganda",
  "Uruguay",
  "Uzbekistán",
  "Vanuatu",
  "Vaticano (Santa Sede)",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Yibuti",
  "Zambia",
  "Zimbabue",
] as const;
