// Listas públicas y estables: evita diferencias de ICU entre servidor y navegador.
export const COUNTRY_OPTIONS = [
  {
    code: "AF",
    name: "Afganistán",
  },
  {
    code: "AL",
    name: "Albania",
  },
  {
    code: "DE",
    name: "Alemania",
  },
  {
    code: "AD",
    name: "Andorra",
  },
  {
    code: "AO",
    name: "Angola",
  },
  {
    code: "AI",
    name: "Anguila",
  },
  {
    code: "AQ",
    name: "Antártida",
  },
  {
    code: "AG",
    name: "Antigua y Barbuda",
  },
  {
    code: "SA",
    name: "Arabia Saudí",
  },
  {
    code: "DZ",
    name: "Argelia",
  },
  {
    code: "AR",
    name: "Argentina",
  },
  {
    code: "AM",
    name: "Armenia",
  },
  {
    code: "AW",
    name: "Aruba",
  },
  {
    code: "AU",
    name: "Australia",
  },
  {
    code: "AT",
    name: "Austria",
  },
  {
    code: "AZ",
    name: "Azerbaiyán",
  },
  {
    code: "BS",
    name: "Bahamas",
  },
  {
    code: "BD",
    name: "Bangladés",
  },
  {
    code: "BB",
    name: "Barbados",
  },
  {
    code: "BH",
    name: "Baréin",
  },
  {
    code: "BE",
    name: "Bélgica",
  },
  {
    code: "BZ",
    name: "Belice",
  },
  {
    code: "BJ",
    name: "Benín",
  },
  {
    code: "BM",
    name: "Bermudas",
  },
  {
    code: "BY",
    name: "Bielorrusia",
  },
  {
    code: "BO",
    name: "Bolivia",
  },
  {
    code: "BA",
    name: "Bosnia y Herzegovina",
  },
  {
    code: "BW",
    name: "Botsuana",
  },
  {
    code: "BR",
    name: "Brasil",
  },
  {
    code: "BN",
    name: "Brunéi",
  },
  {
    code: "BG",
    name: "Bulgaria",
  },
  {
    code: "BF",
    name: "Burkina Faso",
  },
  {
    code: "BI",
    name: "Burundi",
  },
  {
    code: "BT",
    name: "Bután",
  },
  {
    code: "CV",
    name: "Cabo Verde",
  },
  {
    code: "KH",
    name: "Camboya",
  },
  {
    code: "CM",
    name: "Camerún",
  },
  {
    code: "CA",
    name: "Canadá",
  },
  {
    code: "BQ",
    name: "Caribe neerlandés",
  },
  {
    code: "QA",
    name: "Catar",
  },
  {
    code: "TD",
    name: "Chad",
  },
  {
    code: "CZ",
    name: "Chequia",
  },
  {
    code: "CL",
    name: "Chile",
  },
  {
    code: "CN",
    name: "China",
  },
  {
    code: "CY",
    name: "Chipre",
  },
  {
    code: "VA",
    name: "Ciudad del Vaticano",
  },
  {
    code: "CO",
    name: "Colombia",
  },
  {
    code: "KM",
    name: "Comoras",
  },
  {
    code: "CG",
    name: "Congo",
  },
  {
    code: "KP",
    name: "Corea del Norte",
  },
  {
    code: "KR",
    name: "Corea del Sur",
  },
  {
    code: "CR",
    name: "Costa Rica",
  },
  {
    code: "CI",
    name: "Côte d’Ivoire",
  },
  {
    code: "HR",
    name: "Croacia",
  },
  {
    code: "CU",
    name: "Cuba",
  },
  {
    code: "CW",
    name: "Curazao",
  },
  {
    code: "DK",
    name: "Dinamarca",
  },
  {
    code: "DM",
    name: "Dominica",
  },
  {
    code: "EC",
    name: "Ecuador",
  },
  {
    code: "EG",
    name: "Egipto",
  },
  {
    code: "SV",
    name: "El Salvador",
  },
  {
    code: "AE",
    name: "Emiratos Árabes Unidos",
  },
  {
    code: "ER",
    name: "Eritrea",
  },
  {
    code: "SK",
    name: "Eslovaquia",
  },
  {
    code: "SI",
    name: "Eslovenia",
  },
  {
    code: "ES",
    name: "España",
  },
  {
    code: "US",
    name: "Estados Unidos",
  },
  {
    code: "EE",
    name: "Estonia",
  },
  {
    code: "SZ",
    name: "Esuatini",
  },
  {
    code: "ET",
    name: "Etiopía",
  },
  {
    code: "PH",
    name: "Filipinas",
  },
  {
    code: "FI",
    name: "Finlandia",
  },
  {
    code: "FJ",
    name: "Fiyi",
  },
  {
    code: "FR",
    name: "Francia",
  },
  {
    code: "GA",
    name: "Gabón",
  },
  {
    code: "GM",
    name: "Gambia",
  },
  {
    code: "GE",
    name: "Georgia",
  },
  {
    code: "GH",
    name: "Ghana",
  },
  {
    code: "GI",
    name: "Gibraltar",
  },
  {
    code: "GD",
    name: "Granada",
  },
  {
    code: "GR",
    name: "Grecia",
  },
  {
    code: "GL",
    name: "Groenlandia",
  },
  {
    code: "GP",
    name: "Guadalupe",
  },
  {
    code: "GU",
    name: "Guam",
  },
  {
    code: "GT",
    name: "Guatemala",
  },
  {
    code: "GF",
    name: "Guayana Francesa",
  },
  {
    code: "GG",
    name: "Guernesey",
  },
  {
    code: "GN",
    name: "Guinea",
  },
  {
    code: "GQ",
    name: "Guinea Ecuatorial",
  },
  {
    code: "GW",
    name: "Guinea-Bisáu",
  },
  {
    code: "GY",
    name: "Guyana",
  },
  {
    code: "HT",
    name: "Haití",
  },
  {
    code: "HN",
    name: "Honduras",
  },
  {
    code: "HU",
    name: "Hungría",
  },
  {
    code: "IN",
    name: "India",
  },
  {
    code: "ID",
    name: "Indonesia",
  },
  {
    code: "IQ",
    name: "Irak",
  },
  {
    code: "IR",
    name: "Irán",
  },
  {
    code: "IE",
    name: "Irlanda",
  },
  {
    code: "BV",
    name: "Isla Bouvet",
  },
  {
    code: "IM",
    name: "Isla de Man",
  },
  {
    code: "CX",
    name: "Isla de Navidad",
  },
  {
    code: "NF",
    name: "Isla Norfolk",
  },
  {
    code: "IS",
    name: "Islandia",
  },
  {
    code: "AX",
    name: "Islas Aland",
  },
  {
    code: "KY",
    name: "Islas Caimán",
  },
  {
    code: "CC",
    name: "Islas Cocos",
  },
  {
    code: "CK",
    name: "Islas Cook",
  },
  {
    code: "FO",
    name: "Islas Feroe",
  },
  {
    code: "GS",
    name: "Islas Georgia del Sur y Sandwich del Sur",
  },
  {
    code: "HM",
    name: "Islas Heard y McDonald",
  },
  {
    code: "FK",
    name: "Islas Malvinas",
  },
  {
    code: "MP",
    name: "Islas Marianas del Norte",
  },
  {
    code: "MH",
    name: "Islas Marshall",
  },
  {
    code: "UM",
    name: "Islas menores alejadas de EE. UU.",
  },
  {
    code: "PN",
    name: "Islas Pitcairn",
  },
  {
    code: "SB",
    name: "Islas Salomón",
  },
  {
    code: "TC",
    name: "Islas Turcas y Caicos",
  },
  {
    code: "VG",
    name: "Islas Vírgenes Británicas",
  },
  {
    code: "VI",
    name: "Islas Vírgenes de EE. UU.",
  },
  {
    code: "IL",
    name: "Israel",
  },
  {
    code: "IT",
    name: "Italia",
  },
  {
    code: "JM",
    name: "Jamaica",
  },
  {
    code: "JP",
    name: "Japón",
  },
  {
    code: "JE",
    name: "Jersey",
  },
  {
    code: "JO",
    name: "Jordania",
  },
  {
    code: "KZ",
    name: "Kazajistán",
  },
  {
    code: "KE",
    name: "Kenia",
  },
  {
    code: "KG",
    name: "Kirguistán",
  },
  {
    code: "KI",
    name: "Kiribati",
  },
  {
    code: "KW",
    name: "Kuwait",
  },
  {
    code: "LA",
    name: "Laos",
  },
  {
    code: "LS",
    name: "Lesoto",
  },
  {
    code: "LV",
    name: "Letonia",
  },
  {
    code: "LB",
    name: "Líbano",
  },
  {
    code: "LR",
    name: "Liberia",
  },
  {
    code: "LY",
    name: "Libia",
  },
  {
    code: "LI",
    name: "Liechtenstein",
  },
  {
    code: "LT",
    name: "Lituania",
  },
  {
    code: "LU",
    name: "Luxemburgo",
  },
  {
    code: "MK",
    name: "Macedonia del Norte",
  },
  {
    code: "MG",
    name: "Madagascar",
  },
  {
    code: "MY",
    name: "Malasia",
  },
  {
    code: "MW",
    name: "Malaui",
  },
  {
    code: "MV",
    name: "Maldivas",
  },
  {
    code: "ML",
    name: "Mali",
  },
  {
    code: "MT",
    name: "Malta",
  },
  {
    code: "MA",
    name: "Marruecos",
  },
  {
    code: "MQ",
    name: "Martinica",
  },
  {
    code: "MU",
    name: "Mauricio",
  },
  {
    code: "MR",
    name: "Mauritania",
  },
  {
    code: "YT",
    name: "Mayotte",
  },
  {
    code: "MX",
    name: "México",
  },
  {
    code: "FM",
    name: "Micronesia",
  },
  {
    code: "MD",
    name: "Moldavia",
  },
  {
    code: "MC",
    name: "Mónaco",
  },
  {
    code: "MN",
    name: "Mongolia",
  },
  {
    code: "ME",
    name: "Montenegro",
  },
  {
    code: "MS",
    name: "Montserrat",
  },
  {
    code: "MZ",
    name: "Mozambique",
  },
  {
    code: "MM",
    name: "Myanmar (Birmania)",
  },
  {
    code: "NA",
    name: "Namibia",
  },
  {
    code: "NR",
    name: "Nauru",
  },
  {
    code: "NP",
    name: "Nepal",
  },
  {
    code: "NI",
    name: "Nicaragua",
  },
  {
    code: "NE",
    name: "Níger",
  },
  {
    code: "NG",
    name: "Nigeria",
  },
  {
    code: "NU",
    name: "Niue",
  },
  {
    code: "NO",
    name: "Noruega",
  },
  {
    code: "NC",
    name: "Nueva Caledonia",
  },
  {
    code: "NZ",
    name: "Nueva Zelanda",
  },
  {
    code: "OM",
    name: "Omán",
  },
  {
    code: "NL",
    name: "Países Bajos",
  },
  {
    code: "PK",
    name: "Pakistán",
  },
  {
    code: "PW",
    name: "Palaos",
  },
  {
    code: "PA",
    name: "Panamá",
  },
  {
    code: "PG",
    name: "Papúa Nueva Guinea",
  },
  {
    code: "PY",
    name: "Paraguay",
  },
  {
    code: "PE",
    name: "Perú",
  },
  {
    code: "PF",
    name: "Polinesia Francesa",
  },
  {
    code: "PL",
    name: "Polonia",
  },
  {
    code: "PT",
    name: "Portugal",
  },
  {
    code: "PR",
    name: "Puerto Rico",
  },
  {
    code: "HK",
    name: "RAE de Hong Kong (China)",
  },
  {
    code: "MO",
    name: "RAE de Macao (China)",
  },
  {
    code: "GB",
    name: "Reino Unido",
  },
  {
    code: "CF",
    name: "República Centroafricana",
  },
  {
    code: "CD",
    name: "República Democrática del Congo",
  },
  {
    code: "DO",
    name: "República Dominicana",
  },
  {
    code: "RE",
    name: "Reunión",
  },
  {
    code: "RW",
    name: "Ruanda",
  },
  {
    code: "RO",
    name: "Rumanía",
  },
  {
    code: "RU",
    name: "Rusia",
  },
  {
    code: "EH",
    name: "Sáhara Occidental",
  },
  {
    code: "WS",
    name: "Samoa",
  },
  {
    code: "AS",
    name: "Samoa Americana",
  },
  {
    code: "BL",
    name: "San Bartolomé",
  },
  {
    code: "KN",
    name: "San Cristóbal y Nieves",
  },
  {
    code: "SM",
    name: "San Marino",
  },
  {
    code: "MF",
    name: "San Martín",
  },
  {
    code: "PM",
    name: "San Pedro y Miquelón",
  },
  {
    code: "VC",
    name: "San Vicente y las Granadinas",
  },
  {
    code: "SH",
    name: "Santa Elena",
  },
  {
    code: "LC",
    name: "Santa Lucía",
  },
  {
    code: "ST",
    name: "Santo Tomé y Príncipe",
  },
  {
    code: "SN",
    name: "Senegal",
  },
  {
    code: "RS",
    name: "Serbia",
  },
  {
    code: "SC",
    name: "Seychelles",
  },
  {
    code: "SL",
    name: "Sierra Leona",
  },
  {
    code: "SG",
    name: "Singapur",
  },
  {
    code: "SX",
    name: "Sint Maarten",
  },
  {
    code: "SY",
    name: "Siria",
  },
  {
    code: "SO",
    name: "Somalia",
  },
  {
    code: "LK",
    name: "Sri Lanka",
  },
  {
    code: "ZA",
    name: "Sudáfrica",
  },
  {
    code: "SD",
    name: "Sudán",
  },
  {
    code: "SS",
    name: "Sudán del Sur",
  },
  {
    code: "SE",
    name: "Suecia",
  },
  {
    code: "CH",
    name: "Suiza",
  },
  {
    code: "SR",
    name: "Surinam",
  },
  {
    code: "SJ",
    name: "Svalbard y Jan Mayen",
  },
  {
    code: "TH",
    name: "Tailandia",
  },
  {
    code: "TW",
    name: "Taiwán",
  },
  {
    code: "TZ",
    name: "Tanzania",
  },
  {
    code: "TJ",
    name: "Tayikistán",
  },
  {
    code: "IO",
    name: "Territorio Británico del Océano Índico",
  },
  {
    code: "TF",
    name: "Territorios Australes Franceses",
  },
  {
    code: "PS",
    name: "Territorios Palestinos",
  },
  {
    code: "TL",
    name: "Timor-Leste",
  },
  {
    code: "TG",
    name: "Togo",
  },
  {
    code: "TK",
    name: "Tokelau",
  },
  {
    code: "TO",
    name: "Tonga",
  },
  {
    code: "TT",
    name: "Trinidad y Tobago",
  },
  {
    code: "TN",
    name: "Túnez",
  },
  {
    code: "TM",
    name: "Turkmenistán",
  },
  {
    code: "TR",
    name: "Turquía",
  },
  {
    code: "TV",
    name: "Tuvalu",
  },
  {
    code: "UA",
    name: "Ucrania",
  },
  {
    code: "UG",
    name: "Uganda",
  },
  {
    code: "UY",
    name: "Uruguay",
  },
  {
    code: "UZ",
    name: "Uzbekistán",
  },
  {
    code: "VU",
    name: "Vanuatu",
  },
  {
    code: "VE",
    name: "Venezuela",
  },
  {
    code: "VN",
    name: "Vietnam",
  },
  {
    code: "WF",
    name: "Wallis y Futuna",
  },
  {
    code: "YE",
    name: "Yemen",
  },
  {
    code: "DJ",
    name: "Yibuti",
  },
  {
    code: "ZM",
    name: "Zambia",
  },
  {
    code: "ZW",
    name: "Zimbabue",
  },
] as const;
export const TIME_ZONES = [
  "UTC",
  "Africa/Abidjan",
  "Africa/Accra",
  "Africa/Addis_Ababa",
  "Africa/Algiers",
  "Africa/Asmera",
  "Africa/Bamako",
  "Africa/Bangui",
  "Africa/Banjul",
  "Africa/Bissau",
  "Africa/Blantyre",
  "Africa/Brazzaville",
  "Africa/Bujumbura",
  "Africa/Cairo",
  "Africa/Casablanca",
  "Africa/Ceuta",
  "Africa/Conakry",
  "Africa/Dakar",
  "Africa/Dar_es_Salaam",
  "Africa/Djibouti",
  "Africa/Douala",
  "Africa/El_Aaiun",
  "Africa/Freetown",
  "Africa/Gaborone",
  "Africa/Harare",
  "Africa/Johannesburg",
  "Africa/Juba",
  "Africa/Kampala",
  "Africa/Khartoum",
  "Africa/Kigali",
  "Africa/Kinshasa",
  "Africa/Lagos",
  "Africa/Libreville",
  "Africa/Lome",
  "Africa/Luanda",
  "Africa/Lubumbashi",
  "Africa/Lusaka",
  "Africa/Malabo",
  "Africa/Maputo",
  "Africa/Maseru",
  "Africa/Mbabane",
  "Africa/Mogadishu",
  "Africa/Monrovia",
  "Africa/Nairobi",
  "Africa/Ndjamena",
  "Africa/Niamey",
  "Africa/Nouakchott",
  "Africa/Ouagadougou",
  "Africa/Porto-Novo",
  "Africa/Sao_Tome",
  "Africa/Tripoli",
  "Africa/Tunis",
  "Africa/Windhoek",
  "America/Adak",
  "America/Anchorage",
  "America/Anguilla",
  "America/Antigua",
  "America/Araguaina",
  "America/Argentina/La_Rioja",
  "America/Argentina/Rio_Gallegos",
  "America/Argentina/Salta",
  "America/Argentina/San_Juan",
  "America/Argentina/San_Luis",
  "America/Argentina/Tucuman",
  "America/Argentina/Ushuaia",
  "America/Aruba",
  "America/Asuncion",
  "America/Bahia",
  "America/Bahia_Banderas",
  "America/Barbados",
  "America/Belem",
  "America/Belize",
  "America/Blanc-Sablon",
  "America/Boa_Vista",
  "America/Bogota",
  "America/Boise",
  "America/Buenos_Aires",
  "America/Cambridge_Bay",
  "America/Campo_Grande",
  "America/Cancun",
  "America/Caracas",
  "America/Catamarca",
  "America/Cayenne",
  "America/Cayman",
  "America/Chicago",
  "America/Chihuahua",
  "America/Ciudad_Juarez",
  "America/Coral_Harbour",
  "America/Cordoba",
  "America/Costa_Rica",
  "America/Coyhaique",
  "America/Creston",
  "America/Cuiaba",
  "America/Curacao",
  "America/Danmarkshavn",
  "America/Dawson",
  "America/Dawson_Creek",
  "America/Denver",
  "America/Detroit",
  "America/Dominica",
  "America/Edmonton",
  "America/Eirunepe",
  "America/El_Salvador",
  "America/Fort_Nelson",
  "America/Fortaleza",
  "America/Glace_Bay",
  "America/Godthab",
  "America/Goose_Bay",
  "America/Grand_Turk",
  "America/Grenada",
  "America/Guadeloupe",
  "America/Guatemala",
  "America/Guayaquil",
  "America/Guyana",
  "America/Halifax",
  "America/Havana",
  "America/Hermosillo",
  "America/Indiana/Knox",
  "America/Indiana/Marengo",
  "America/Indiana/Petersburg",
  "America/Indiana/Tell_City",
  "America/Indiana/Vevay",
  "America/Indiana/Vincennes",
  "America/Indiana/Winamac",
  "America/Indianapolis",
  "America/Inuvik",
  "America/Iqaluit",
  "America/Jamaica",
  "America/Jujuy",
  "America/Juneau",
  "America/Kentucky/Monticello",
  "America/Kralendijk",
  "America/La_Paz",
  "America/Lima",
  "America/Los_Angeles",
  "America/Louisville",
  "America/Lower_Princes",
  "America/Maceio",
  "America/Managua",
  "America/Manaus",
  "America/Marigot",
  "America/Martinique",
  "America/Matamoros",
  "America/Mazatlan",
  "America/Mendoza",
  "America/Menominee",
  "America/Merida",
  "America/Metlakatla",
  "America/Mexico_City",
  "America/Miquelon",
  "America/Moncton",
  "America/Monterrey",
  "America/Montevideo",
  "America/Montserrat",
  "America/Nassau",
  "America/New_York",
  "America/Nome",
  "America/Noronha",
  "America/North_Dakota/Beulah",
  "America/North_Dakota/Center",
  "America/North_Dakota/New_Salem",
  "America/Ojinaga",
  "America/Panama",
  "America/Paramaribo",
  "America/Phoenix",
  "America/Port-au-Prince",
  "America/Port_of_Spain",
  "America/Porto_Velho",
  "America/Puerto_Rico",
  "America/Punta_Arenas",
  "America/Rankin_Inlet",
  "America/Recife",
  "America/Regina",
  "America/Resolute",
  "America/Rio_Branco",
  "America/Santarem",
  "America/Santiago",
  "America/Santo_Domingo",
  "America/Sao_Paulo",
  "America/Scoresbysund",
  "America/Sitka",
  "America/St_Barthelemy",
  "America/St_Johns",
  "America/St_Kitts",
  "America/St_Lucia",
  "America/St_Thomas",
  "America/St_Vincent",
  "America/Swift_Current",
  "America/Tegucigalpa",
  "America/Thule",
  "America/Tijuana",
  "America/Toronto",
  "America/Tortola",
  "America/Vancouver",
  "America/Whitehorse",
  "America/Winnipeg",
  "America/Yakutat",
  "Antarctica/Casey",
  "Antarctica/Davis",
  "Antarctica/DumontDUrville",
  "Antarctica/Macquarie",
  "Antarctica/Mawson",
  "Antarctica/McMurdo",
  "Antarctica/Palmer",
  "Antarctica/Rothera",
  "Antarctica/Syowa",
  "Antarctica/Troll",
  "Antarctica/Vostok",
  "Arctic/Longyearbyen",
  "Asia/Aden",
  "Asia/Almaty",
  "Asia/Amman",
  "Asia/Anadyr",
  "Asia/Aqtau",
  "Asia/Aqtobe",
  "Asia/Ashgabat",
  "Asia/Atyrau",
  "Asia/Baghdad",
  "Asia/Bahrain",
  "Asia/Baku",
  "Asia/Bangkok",
  "Asia/Barnaul",
  "Asia/Beirut",
  "Asia/Bishkek",
  "Asia/Brunei",
  "Asia/Calcutta",
  "Asia/Chita",
  "Asia/Colombo",
  "Asia/Damascus",
  "Asia/Dhaka",
  "Asia/Dili",
  "Asia/Dubai",
  "Asia/Dushanbe",
  "Asia/Famagusta",
  "Asia/Gaza",
  "Asia/Hebron",
  "Asia/Hong_Kong",
  "Asia/Hovd",
  "Asia/Irkutsk",
  "Asia/Jakarta",
  "Asia/Jayapura",
  "Asia/Jerusalem",
  "Asia/Kabul",
  "Asia/Kamchatka",
  "Asia/Karachi",
  "Asia/Katmandu",
  "Asia/Khandyga",
  "Asia/Krasnoyarsk",
  "Asia/Kuala_Lumpur",
  "Asia/Kuching",
  "Asia/Kuwait",
  "Asia/Macau",
  "Asia/Magadan",
  "Asia/Makassar",
  "Asia/Manila",
  "Asia/Muscat",
  "Asia/Nicosia",
  "Asia/Novokuznetsk",
  "Asia/Novosibirsk",
  "Asia/Omsk",
  "Asia/Oral",
  "Asia/Phnom_Penh",
  "Asia/Pontianak",
  "Asia/Pyongyang",
  "Asia/Qatar",
  "Asia/Qostanay",
  "Asia/Qyzylorda",
  "Asia/Rangoon",
  "Asia/Riyadh",
  "Asia/Saigon",
  "Asia/Sakhalin",
  "Asia/Samarkand",
  "Asia/Seoul",
  "Asia/Shanghai",
  "Asia/Singapore",
  "Asia/Srednekolymsk",
  "Asia/Taipei",
  "Asia/Tashkent",
  "Asia/Tbilisi",
  "Asia/Tehran",
  "Asia/Thimphu",
  "Asia/Tokyo",
  "Asia/Tomsk",
  "Asia/Ulaanbaatar",
  "Asia/Urumqi",
  "Asia/Ust-Nera",
  "Asia/Vientiane",
  "Asia/Vladivostok",
  "Asia/Yakutsk",
  "Asia/Yekaterinburg",
  "Asia/Yerevan",
  "Atlantic/Azores",
  "Atlantic/Bermuda",
  "Atlantic/Canary",
  "Atlantic/Cape_Verde",
  "Atlantic/Faeroe",
  "Atlantic/Madeira",
  "Atlantic/Reykjavik",
  "Atlantic/South_Georgia",
  "Atlantic/St_Helena",
  "Atlantic/Stanley",
  "Australia/Adelaide",
  "Australia/Brisbane",
  "Australia/Broken_Hill",
  "Australia/Darwin",
  "Australia/Eucla",
  "Australia/Hobart",
  "Australia/Lindeman",
  "Australia/Lord_Howe",
  "Australia/Melbourne",
  "Australia/Perth",
  "Australia/Sydney",
  "Europe/Amsterdam",
  "Europe/Andorra",
  "Europe/Astrakhan",
  "Europe/Athens",
  "Europe/Belgrade",
  "Europe/Berlin",
  "Europe/Bratislava",
  "Europe/Brussels",
  "Europe/Bucharest",
  "Europe/Budapest",
  "Europe/Busingen",
  "Europe/Chisinau",
  "Europe/Copenhagen",
  "Europe/Dublin",
  "Europe/Gibraltar",
  "Europe/Guernsey",
  "Europe/Helsinki",
  "Europe/Isle_of_Man",
  "Europe/Istanbul",
  "Europe/Jersey",
  "Europe/Kaliningrad",
  "Europe/Kiev",
  "Europe/Kirov",
  "Europe/Lisbon",
  "Europe/Ljubljana",
  "Europe/London",
  "Europe/Luxembourg",
  "Europe/Madrid",
  "Europe/Malta",
  "Europe/Mariehamn",
  "Europe/Minsk",
  "Europe/Monaco",
  "Europe/Moscow",
  "Europe/Oslo",
  "Europe/Paris",
  "Europe/Podgorica",
  "Europe/Prague",
  "Europe/Riga",
  "Europe/Rome",
  "Europe/Samara",
  "Europe/San_Marino",
  "Europe/Sarajevo",
  "Europe/Saratov",
  "Europe/Simferopol",
  "Europe/Skopje",
  "Europe/Sofia",
  "Europe/Stockholm",
  "Europe/Tallinn",
  "Europe/Tirane",
  "Europe/Ulyanovsk",
  "Europe/Vaduz",
  "Europe/Vatican",
  "Europe/Vienna",
  "Europe/Vilnius",
  "Europe/Volgograd",
  "Europe/Warsaw",
  "Europe/Zagreb",
  "Europe/Zurich",
  "Indian/Antananarivo",
  "Indian/Chagos",
  "Indian/Christmas",
  "Indian/Cocos",
  "Indian/Comoro",
  "Indian/Kerguelen",
  "Indian/Mahe",
  "Indian/Maldives",
  "Indian/Mauritius",
  "Indian/Mayotte",
  "Indian/Reunion",
  "Pacific/Apia",
  "Pacific/Auckland",
  "Pacific/Bougainville",
  "Pacific/Chatham",
  "Pacific/Easter",
  "Pacific/Efate",
  "Pacific/Enderbury",
  "Pacific/Fakaofo",
  "Pacific/Fiji",
  "Pacific/Funafuti",
  "Pacific/Galapagos",
  "Pacific/Gambier",
  "Pacific/Guadalcanal",
  "Pacific/Guam",
  "Pacific/Honolulu",
  "Pacific/Kiritimati",
  "Pacific/Kosrae",
  "Pacific/Kwajalein",
  "Pacific/Majuro",
  "Pacific/Marquesas",
  "Pacific/Midway",
  "Pacific/Nauru",
  "Pacific/Niue",
  "Pacific/Norfolk",
  "Pacific/Noumea",
  "Pacific/Pago_Pago",
  "Pacific/Palau",
  "Pacific/Pitcairn",
  "Pacific/Ponape",
  "Pacific/Port_Moresby",
  "Pacific/Rarotonga",
  "Pacific/Saipan",
  "Pacific/Tahiti",
  "Pacific/Tarawa",
  "Pacific/Tongatapu",
  "Pacific/Truk",
  "Pacific/Wake",
  "Pacific/Wallis",
] as const;
export function countryName(code: string): string {
  return COUNTRY_OPTIONS.find((country) => country.code === code)?.name || code;
}
