/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=WorkerBindings src/worker-bindings.d.ts` (hash: 84bb3203fb51071d4efb9dd7a85cd248)
interface __BaseEnv_WorkerBindings {
	NEXT_INC_CACHE_KV: KVNamespace;
	DB: D1Database;
	NEXT_TAG_CACHE_D1: D1Database;
	ASSETS: Fetcher;
	NEXT_PUBLIC_SITE_URL: string;
	GOOGLE_SITE_VERIFICATION: string;
	PUBLIC_CONTACT_EMAILS: string;
	PRIVACY_CONTACT_EMAIL: string;
	ABUSE_CONTACT_EMAIL: string;
	NIDO_DB_TARGET: string;
	CF_BEACON_TOKEN: string;
	TURNSTILE_SITE_KEY: string;
	NIDO_PLATFORM_FEE_CENTS: string;
	NIDO_PRACTICE_ENABLED: string;
	NIDO_MEMBERSHIP_BILLING_ENABLED: string;
	NIDO_CARE_BILLING_ENABLED: string;
	NIDO_CALL_CAPTURE_ENABLED: string;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	ADMIN_EMAILS: string;
	DATABASE_URL: string;
	CONTACT_FROM_EMAIL: string;
	NOTIFICATION_EMAIL: string;
	NEXT_PUBLIC_GOOGLE_AUTH_ENABLED: string;
	REQUIRE_EMAIL_VERIFICATION: string;
	Conversation: DurableObjectNamespace<import("../custom-worker").Conversation>;
	NEXT_CACHE_DO_QUEUE: DurableObjectNamespace<import("../custom-worker").DOQueueHandler>;
	WORKER_SELF_REFERENCE: Service<typeof import("../custom-worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../custom-worker");
		durableNamespaces: "Conversation" | "DOQueueHandler";
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXT_PUBLIC_SITE_URL" | "GOOGLE_SITE_VERIFICATION" | "PUBLIC_CONTACT_EMAILS" | "PRIVACY_CONTACT_EMAIL" | "ABUSE_CONTACT_EMAIL" | "NIDO_DB_TARGET" | "CF_BEACON_TOKEN" | "TURNSTILE_SITE_KEY" | "NIDO_PLATFORM_FEE_CENTS" | "NIDO_PRACTICE_ENABLED" | "NIDO_MEMBERSHIP_BILLING_ENABLED" | "NIDO_CARE_BILLING_ENABLED" | "NIDO_CALL_CAPTURE_ENABLED" | "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "ADMIN_EMAILS" | "DATABASE_URL" | "CONTACT_FROM_EMAIL" | "NOTIFICATION_EMAIL" | "NEXT_PUBLIC_GOOGLE_AUTH_ENABLED" | "REQUIRE_EMAIL_VERIFICATION">> {}
}
